### ISSUE TITLE
The "langref" folder is missing

### ISSUE THREAD

**Issue by raducoravu** [hyperwrite/DITAStyleGuide#8]
There are a bunch of references to resources like "langref/abbrevlist.dita" but there is no "langref" folder in the project

**Comment by hyperwrite** [comment]
Hi Radu. I think all of those references to the langref folder are conditionalised, as they are not intended to be included in the public DITA Style Guide. I'm pretty sure the condition is <prop att="product" val="academic_only" action="exclude" alt="product - academic_only" />. The topics in the langref folder would be the DITA Language Reference files, and I didn't want to include them in this repository. For some specific outputs from the same source collection, primarily for academic purposes, the Style Guide can be cross-referenced to the Language Reference and also the Microsoft Manual of Style.

**Comment by raducoravu** [comment]
Thanks for the reply Tony.
There does not appear to be a ditaval filter file in the project if the intention was to use such a filter for publishing.
We basically want to re-publish the DITA Style guide as right now it is in an older WebHelp Classic output format:
https://www.oxygenxml.com/dita/styleguide/webhelp-feedback/

and we want to publish it with our WebHelp Responsive templates which look better.
The initial content @georgebina got from you a long while back contained the "langref" folder I think, can we use it in our published WebHelp Responsive edition of the DITA Style guide or should we publish only the contents available in this GitHub project?

**Comment by hyperwrite** [comment]
I can't find the ditaval file myself! I may have just given the instruction to George, rather than the file. It's a long time ago now!! My /langref folder contains the reference for DITA 1.1. I wonder whether that is now too old to include? I think the structure of the files changed in 1.3, so I don't think it would be as simple as replacing that folder with the 1.3 language reference. My main concern is that any Rationale sections are excluded, as I haven't sought permission from the people mentioned there. These sections are really for my own reference, and are not for publication. You can see such a section element in, for example, Cross_Referencing\c_Related_Links_Section.dita. All of these are marked with **audience="contributor"**. So that needs to be excluded in the ditaval. Also, I think there are cross-references to the Microsoft Manual of Style, but I recall these are only through reltables. I don't have any copyright permission to use anything from that Manual of Style, so these shouldn't be published either.

**Comment by raducoravu** [comment]
Ok, we'll try to create our own ditaval filter file then.

**Comment by raducoravu** [comment]
I think the ditaval should look something like this:

    <val>
        <prop action="exclude" att="audience" val="contributor"/>
      <prop action="exclude" att="product" val="academic_only"/>
    </val>

**Comment by hyperwrite** [comment]
Ah ha! Found my email to George from 2013! It said:

_There are a few points to note with the source files too. The following attribute settings must be excluded from the output:

audience="contributor"  >>> EXCLUDE
product="academic_only" >>> EXCLUDE

The content with that mark-up is used as an audit trail for rules in the guide, or is intended for use in academic publications.

Further, you will find in the main bookmap a reference to a reltable ditamap called artefact_langref_reltable.ditamap. This map contains the relationships between The DITA Style Guide and the DITA Language Reference (v1.1). This might be useful to you when you are associating topics with elements._

**Comment by raducoravu** [comment]
Ok, I'm closing the issue then.
